apiVersion: v1
kind: CronJob
metadata:
  name: renovate
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              envFrom:
                - secretRef:
                    name: renovate-secrets
