apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            envFrom:
              - secretRef:
                  name: renovate-secrets
