apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: created-secret
    creationPolicy: Owner
  data:
    - secretKey: test-key
      remoteRef:
        key: homelab/renovate
