apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: aws-sm-secrets
  data:
    - secretKey: secret-access-key
      remoteRef:
        key: external-secrets/aws-sm-secrets
        property: secret-access-key
    - secretKey: access-key
      remoteRef:
        key: external-secrets/aws-sm-secrets
        property: access-key
