apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coredns
resources:
  - release.yaml
  - namespace.yaml
  - repository.yaml

configMapGenerator:
  - name: coredns-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomize-config.yaml
