apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
spec:
  chart:
    spec:
      chart: coredns
      version: 1.44.*
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coredns
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: coredns-values
      valuesKey: values.yaml
