isClusterService: false

service:
  type: LoadBalancer
  loadBalancerClass: tailscale
  annotations:
    tailscale.com/hostname: coredns
    tailscale.com/expose: "true"

prometheus:
  monitor:
    enabled: true
    namespace: coredns
    interval: 30s
  service:
    enabled: true

servers:
  - zones:
      - zone: cluster.local
      - zone: in-addr.arpa
      - zone: ip6.arpa
    port: 53
    plugins:
      - name: errors
      - name: health
        configBlock: |
          lameduck 10s
      - name: ready
      - name: kubernetes
        parameters: "cluster.local in-addr.arpa ip6.arpa"
        configBlock: |
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      - name: prometheus
        parameters: "0.0.0.0:9153"
      - name: cache
        parameters: "30"
      - name: loop
      - name: reload
      - name: forward
        parameters: ". 100.100.100.100"
  - zones:
      - zone: lan
    port: 53
    plugins:
      - name: errors
      - name: ready
      - name: k8s_external
      - name: cache
        parameters: "30"
      - name: forward
        parameters: ". 100.100.100.100"
