isClusterService: false

service:
  type: LoadBalancer
  loadBalancerClass: tailscale
  annotations:
    tailscale.com/hostname: coredns
    tailscale.com/expose: "true"

prometheus:
  monitor:
    enabled: true
    namespace: coredns
    interval: 30s
  service:
    enabled: true

servers:
  # Authoritative server for homelab.lan
  - zones:
      - zone: "homelab.lan."
    port: 53
    plugins:
      - name: errors
      - name: health
        configBlock: |
          lameduck 10s
      - name: ready
      - name: rewrite
        configBlock: |
          name suffix homelab.lan svc.cluster.local
          answer name suffix svc.cluster.local homelab.lan
      - name: kubernetes
        parameters: "cluster.local in-addr.arpa ip6.arpa"
        configBlock: |
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      - name: prometheus
        parameters: "0.0.0.0:9153"
      - name: cache
        parameters: "30"
      - name: loop
      - name: reload

  - zones:
      - zone: "."
    port: 53
    plugins:
      - name: errors
      - name: health
        configBlock: |
          lameduck 10s
      - name: ready
      - name: prometheus
        parameters: "0.0.0.0:9153"
      - name: cache
        parameters: "30"
      - name: loop
      - name: reload
      - name: forward
        parameters: ". /etc/resolv.conf"
