apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
spec:
  chart:
    spec:
      chart: kubernetes-gitlab-demo
      version: 0.1.29
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitlab
  interval: 1m0s
