apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
resources:
  - ../../base/tailscale/
  - namespace.yaml
  - oauth-secrets.yaml
patches:
  - path: patch-release.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: tailscale
