apiVersion: v1
data:
    password: ENC[AES256_GCM,data:8P06IMT2DdcLsNHGkx+HZesqLiu030wY,iv:k6n70VWEm6kGuYFBDeUbbdCKlz3Bo4isD/UhhYzWKBQ=,tag:179xiROv+a3hNppojzFtWg==,type:str]
kind: Secret
metadata:
    name: grafana-secrets
sops:
    age:
        - recipient: age1zaxuutahx8tae86pqze8q8upmvnwtpdzjk3ljaxlz4emrclv3csqf94cdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ0pDVDRvY1VvTThBTTE1
            SlB0NVBSeTdZcnFPa25NZW5WSFo3NUM0Q2xRCldyajJwQVp2Tmx1ZGxkSnVJYjh0
            NzNrSzlQTlJTdHVxUk5ZaWhhekxlU0EKLS0tIFo5Rit3SFJaajY0ZVR3aGt0bWpM
            WmtWUWM3ZnNrUlUrRUZLc1h6TVZqancKV1zUBqMQZOz/icuTL95NJZJ1zXKdOIkA
            I4Jgm/15tCLPAgscpyifoeMjMHo88YSCwd/GIu98qE1Ud1Spm705OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T19:46:49Z"
    mac: ENC[AES256_GCM,data:+zBNlhZWvo8yJ3Sc7ed78aJK94zJc6JjZTb4AFxTcUT9EFSIL/R0l2yPdIBouBlb6vsUD8KUscn/KrALu07+g7ItMZSpapoMffIRGg6+53swnlkCW0ieJU2EjoBRuLgObb6ju4lThfx1oo6KKPEniHhAzLNgP+XDW8UY4DYhEwg=,iv:D5jVK6zQLx8X5T5cjrLE+wmLfNraVYgEwnieuc/3peE=,tag:/9evvNh1yGR5fbomIX4frQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
