apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chart:
    spec:
      sourceRef:
        namespace: monitoring
  valuesFrom:
    - kind: Secret
      name: grafana-secrets
      valuesKey: password
      targetPath: grafana.adminPassword
