apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chart:
    spec:
      sourceRef:
        namespace: monitoring
  values:
    grafana:
      admin:
        existingSecret: grafana-secrets
        passwordKey: password
