apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
spec:
  chart:
    spec:
      sourceRef:
        namespace: coredns
  values:
    servers:
      - zones:
          - zone: .
        plugins:
          - name: errors
          - name: health
            parameters: "lameduck 10s"
          - name: ready
          - name: rewrite
            parameters: "name grafana.local grafana.monitoring.svc.cluster.local"
          - name: kubernetes
            parameters: "cluster.local in-addr.arpa ip6.arpa"
            configBlock: |
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
          - name: prometheus
            parameters: "0.0.0.0:9153"
          - name: forward
            parameters: ". /etc/resolv.conf"
          - name: cache
            parameters: "30"
          - name: loop
          - name: reload
          - name: loadbalance
