apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - ../../base/longhorn/
  - namespace.yaml
patches:
  - path: patch-release
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: longhorn
