apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      version: 1.88.*
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
  interval: 1m0s
