apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      version: 1.88.*
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
  valuesFrom:
    - kind: Secret
      name: tailscale-secrets
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-secrets
      valuesKey: client_secret
      targetPath: oauth.clientSecret
  interval: 1m0s
