apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: tailscale-secrets
  dataFrom:
    - extract:
        key: homelab/tailscale
