apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: renovate-secrets
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: homelab/renovate
